# Generated by Django 4.2.1 on 2023-06-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_portfolio_consanswers_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Konstruktor',
            new_name='PriKonstruktor',
        ),
        migrations.RenameField(
            model_name='consanswers',
            old_name='title',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='consanswers',
            name='consa1',
        ),
        migrations.RemoveField(
            model_name='consanswers',
            name='consa2',
        ),
        migrations.RemoveField(
            model_name='consanswers',
            name='consa3',
        ),
        migrations.RemoveField(
            model_name='consanswers',
            name='consa4',
        ),
        migrations.RemoveField(
            model_name='consanswers',
            name='consa5',
        ),
        migrations.AddField(
            model_name='consanswers',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consanswers',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
